apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: static-websites
  name: communitystack-website
  labels:
    app: communitystack-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: communitystack-website
  template:
    metadata:
      labels:
        app: communitystack-website
    spec:
      containers:
      - name: communitystack-website
        image: "ghcr.io/communitystack/www.communitystack.com:trunk"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: static-websites
  name: communitystack-website
  labels:
    app: communitystack-website
spec:
  type: ClusterIP
  selector:
    app: communitystack-website
  ports:
    - protocol: TCP
      name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: static-websites
  name: communitystack-website
  labels:
    app: communitystack-website
spec:
  ingressClassName: caddy
  rules:
  - host: www.communitystack.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: communitystack-website
            port:
              number: 80
  - host: communitystack.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: communitystack-website
            port:
              number: 80
